const PDFDocument = require('pdfkit');

const COLORS = {
  blue: '#2563eb',
  text: '#111827',
  muted: '#6b7280',
  border: '#e5e7eb',
  headerBg: '#f8fafc',
  red: '#ef4444'
};

const money = (n) => `$${Number(n || 0).toFixed(2)}`;

function prettyMonth(yearMonth) {
  const [y, m] = String(yearMonth).split('-').map(Number);
  const date = new Date(y, (m || 1) - 1, 1);
  return date.toLocaleString('en-GB', { month: 'long', year: 'numeric' });
}

function drawSummary(doc, rows) {
  const startX = doc.x;
  rows.forEach(([label, value, valueColor]) => {
    const y = doc.y;
    doc.fontSize(10).fillColor(COLORS.muted).text(label, startX, y, { width: 300, continued: false });
    doc.fontSize(10).fillColor(valueColor || COLORS.text).text(value, startX + 300, y, { width: 195, align: 'right' });
    doc.moveDown(0.4);
  });
  doc.fillColor(COLORS.text);
}

function drawHotelTable(doc, hotels) {
  const columns = [
    { key: 'name', label: 'Hotel', width: 150, align: 'left' },
    { key: 'roomEarnings', label: 'Earnings', width: 90, align: 'right', fmt: money },
    { key: 'singleBookings', label: 'Single', width: 55, align: 'right' },
    { key: 'doubleBookings', label: 'Double', width: 55, align: 'right' },
    { key: 'popularRoomType', label: 'Popular', width: 60, align: 'right' },
    { key: 'cancellations', label: 'Cancelled', width: 75, align: 'right' }
  ];

  const startX = doc.page.margins.left;
  let y = doc.y;

  const rowHeight = 22;
  const drawRow = (cells, opts = {}) => {
    if (y + rowHeight > doc.page.height - doc.page.margins.bottom) {
      doc.addPage();
      y = doc.y;
    }
    if (opts.header) {
      doc.rect(startX, y, columns.reduce((s, c) => s + c.width, 0), rowHeight).fill(COLORS.headerBg);
    }
    let x = startX;
    columns.forEach((col, i) => {
      const text = cells[i];
      doc
        .fontSize(opts.header ? 9 : 9.5)
        .fillColor(opts.header ? COLORS.muted : COLORS.text)
        .text(text, x + 6, y + 6, { width: col.width - 12, align: col.align });
      x += col.width;
    });
    doc.moveTo(startX, y + rowHeight)
      .lineTo(x, y + rowHeight)
      .strokeColor(COLORS.border)
      .lineWidth(1)
      .stroke();
    y += rowHeight;
  };

  drawRow(columns.map(c => c.label), { header: true });
  hotels.forEach(h => {
    drawRow(columns.map(c => (c.fmt ? c.fmt(h[c.key]) : String(h[c.key]))));
  });
  doc.y = y;
  doc.x = startX;
}

function generateReportPdf(stream, { yearMonth, generatedAt, resortName, stats }) {
  const doc = new PDFDocument({ size: 'A4', margin: 50 });
  doc.pipe(stream);

  doc.fillColor(COLORS.blue).fontSize(22).text('E-Hotel Resort', { align: 'center' });
  doc.fillColor(COLORS.text).fontSize(14).text('Monthly Performance Report', { align: 'center' });
  doc.moveDown(0.5);
  doc.fontSize(11).fillColor(COLORS.muted)
    .text(`${resortName || 'Resort'}  •  ${prettyMonth(yearMonth)}`, { align: 'center' });
  doc.fontSize(9)
    .text(`Generated: ${new Date(generatedAt).toLocaleString('en-GB')}`, { align: 'center' });
  doc.moveDown(1);

  doc.moveTo(doc.page.margins.left, doc.y)
    .lineTo(doc.page.width - doc.page.margins.right, doc.y)
    .strokeColor(COLORS.border).lineWidth(1).stroke();
  doc.moveDown(1);

  const r = stats.resort;
  doc.fillColor(COLORS.text).fontSize(14).text('Resort-Wide Summary');
  doc.moveDown(0.5);
  drawSummary(doc, [
    ['Total Room Earnings', money(r.roomEarnings)],
    ['Total Bookings', String(r.totalBookings)],
    ['Single Room Bookings', String(r.singleBookings)],
    ['Double Room Bookings', String(r.doubleBookings)],
    ['Most Popular Room Type', (r.popularRoomType || '-').toUpperCase()],
    ['Total Cancelled Bookings', String(r.cancellations), COLORS.red]
  ]);
  doc.moveDown(1);

  doc.fillColor(COLORS.text).fontSize(14).text('Per-Hotel Breakdown');
  doc.moveDown(0.5);
  if (!stats.hotels || stats.hotels.length === 0) {
    doc.fontSize(10).fillColor(COLORS.muted).text('No hotels found for this resort.');
  } else {
    drawHotelTable(doc, stats.hotels);
  }

  doc.moveDown(2);
  doc.fontSize(8).fillColor(COLORS.muted)
    .text('This report is auto-generated by the E-Hotel Performance Reporting system.', {
      align: 'center'
    });

  doc.end();
}

module.exports = { generateReportPdf, prettyMonth };
